name: Update Go Packages

on:
  schedule:
    - cron: '0 19 * * 0' # Runs every Sunday at 7 PM UTC
  workflow_dispatch: # Allows manual execution

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Update Go packages
        run: go get -u ./...

      - name: Tidy Go modules
        run: go mod tidy

      - name: Verify changes
        run: |
          if git diff --exit-code; then
            echo "No changes to commit"
            exit 0
          fi

      - name: Run tests
        run: go test -v ./...

      - name: Set branch name
        id: vars
        run: echo "BRANCH=update-go-packages-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH
          git add .
          git commit -m "Update Go packages"

      - name: Push changes
        run: git push origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ env.BRANCH }}
          title: Update Go packages
          base: main
          body: |
            This pull request updates all Go packages to their latest versions.